application: yoanngarel822
version: 2
runtime: python
api_version: 1

handlers:
- url: /img/video
  static_dir: img/video
  
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css
  
- url: /javascript
  static_dir: javascript
  
- url: .*
  script: main.py
