application: yoann-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "3d"

handlers:
- url: /
  static_files: main.html
  upload: main.html

- url: /img/video
  static_dir: img/video
  
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css
  
- url: /javascript
  static_dir: javascript
  expiration: "10m"
  
- url: /.*
  script: main.app
